version: '3'

services:
  myservices:
      build: .

      env_file:
      - .env
       #command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      expose:
        - "8000"
       

  nginx:
      image: nginx:alpine

      ports:
       - "8000:8000"

      volumes:
       - ./nginx:/etc/nginx/conf.d

      depends_on:
       - myservices

  db:
    image: 'postgres:latest'
    

    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: Demo@123 
      POSTGRES_DB: final
   

   

   

   



                    
                    